### ISSUE TITLE
thank u so much, can i have the source from heroku?

### ISSUE THREAD

**Issue by faridhwisanggeni** [gnujoow/crud-react-redux#1]

**Comment by gnujoow** [comment]
@faridhwisanggeni 
I have no plan for deploying this project on heroku. if you would like to see how this code works, download this project and type flowing commands on your machine.

```
$ git clone https://github.com/gnujoow/crud-react-redux.git
$ cd crud-react-redux
$ npm install
$ npm start
```

thank you.

**Comment by faridhwisanggeni** [comment]
i'm sory before, i mind the source on the http://reduxblog.herokuapp.com/api
